dirkschumacher/ompr

DESCRIPTION

rename project to ompr

---

R/helper.R
tests/testthat/test-model.R

the bug was caused by expression of the form -x.

Fix bug #13 "-x" causes error

---

DESCRIPTION
R/helper.R
README.md
tests/testthat/test-model.R

The most expensive helper function to standardize ASTs is now not recursive anymore. Fairly small ASTs were already too much for the old recursive implementation.

Speed up equation analysis

---

R/class-model.R
R/helper.R
tests/testthat/test-model.R

The bug lead to unknown variables in sum_exp expression quantifiers.

Fix bug #41

---

R/helper.R

Removed recursive call from public api.

Improve speed

---

DESCRIPTION
R/class-solution.R
tests/testthat/test-solution.R

Instead of returning the actual indexes it returned the factor integer representation
Signed-off-by: Dirk Schumacher <mail@dirk-schumacher.net>

Fix bug in get_solution

---

appveyor.yml

R package oldrel causes problems with curl. Deactivate it for now.

Remove oldrel from appveyor

---

DESCRIPTION
R/class-model.R
README.md

Unnecessary call to pause slowing down the add_constraint method

Remove pause from progress bar

---

DESCRIPTION
R/class-model.R
README.md
tests/testthat/test-set-bounds.R
vignettes/problem-tsp.Rmd

set_bounds now works the same quantified variable is used in different index positions

Fix bug with set_bounds

---

R/class-model.R
tests/testthat/test-model.R

Default bounds of binary vars should be 0/1

Fix bug #83

---

R/model-api.R
tests/testthat/test-model-api.R

The ordering of the variable types was not correct
Fixes https://github.com/dirkschumacher/ompr/issues/112

Fix bug #122

---

DESCRIPTION
R/class-constraint.R
R/class-model.R
R/class-solution.R
R/model-api.R
R/ompr-package.R
man/MIPModel.Rd
man/add_constraint.Rd
man/add_variable.Rd
man/extract_coefficients.Rd
man/extract_constraints.Rd
man/get_solution.Rd
man/new_solution.Rd
man/nvars.Rd
man/objective_function.Rd
man/objective_value.Rd
man/ompr.Rd
man/set_bounds.Rd
man/set_objective.Rd
man/solve_model.Rd
man/solver_status.Rd
man/sum_expr.Rd
man/variable_bounds.Rd
man/variable_keys.Rd
man/variable_types.Rd
src/ompr-init.c
tests/testthat/test-add-constraint.R
tests/testthat/test-model-api.R
tests/testthat/test-model.R
vignettes/problem-graph-coloring.Rmd

Some minor changes before CRAN submission

Make some breaking api changes

---

DESCRIPTION
NEWS.md
R/model-api.R
man/extract_constraints.Rd
man/objective_function.Rd
tests/testthat/test-model-api.R

First step to become more memory efficient. This is necessary to support larger models.
Addresses #147 
WIP

Use sparse matrices/vectors

---

DESCRIPTION
NEWS.md

Increase minimum required R version to 3.3.0

---

DESCRIPTION
NEWS.md
R/helper.R

Change deprecated dplyr function

---

DESCRIPTION
NEWS.md
R/helper.R

Remove dplyr dependency

---

DESCRIPTION
NEWS.md
R/class-solution.R
man/get_solution.Rd
tests/testthat/test-solution-milp.R
tests/testthat/test-solution.R

`get_solution(model, x[i], type = "dual")` now gives you the duals if the model is an LP

Add new interface to access column duals

---

DESCRIPTION
R/class-solution.R
man/get_solution.Rd

Fix typo in docs

---

R/abstract-model-impl.R
R/helper.R
R/linear-optimization-model-impl.R
R/milp-impl.R
R/milp-linearopt-variables.R
R/model-api.R
R/solution-api.R
R/solution-impl.R
tests/testthat/test-add-constraint-milp.R
tests/testthat/test-add-constraint.R
tests/testthat/test-add-variable-milp.R
tests/testthat/test-add-variable.R
tests/testthat/test-linear-constraints.R
tests/testthat/test-linearops.R
tests/testthat/test-model-api-milp.R
tests/testthat/test-model-milp.R
tests/testthat/test-model.R
tests/testthat/test-set-bounds-milp.R
tests/testthat/test-set-bounds.R
tests/testthat/test-solution-milp.R

Use styler

---

DESCRIPTION

listcomp is now on CRAN and progress is not needed anymore.

Updated deps

---

NEWS.md
R/solution-impl.R
tests/testthat/test-solution-linear-optimization-model.R

Previously we assumed integers

Support character indexes in get_solution

---

R/linear-optimization-model-impl.R

Speed up extract constraints

---

DESCRIPTION
NEWS.md
R/solution-api.R

Add solver status "success"

---

R/linear-optimization-model-impl.R

Speed up reduce_coefficients

---

R/linear-optimization-model-impl.R

Faster for large variable collections. About 10%

Set bounds in one batch

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
R/solution-impl.R
tests/testthat/test-model-api-linear-optimization-model.R

Fix Bug #404

---

DESCRIPTION
NEWS.md
R/solution-impl.R
cran-comments.md

Release 1.0.2
